// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bT8Ka81GK0Vhgx9WoKSUHC0Rkp5GEbk',
    appId: '1:539867176389:web:af81d3157471130911bfac',
    messagingSenderId: '539867176389',
    projectId: 'noticefication-5db0f',
    authDomain: 'noticefication-5db0f.firebaseapp.com',
    databaseURL: 'https://noticefication-5db0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noticefication-5db0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8XJMSvQwQUtWiVwWFd6w-Cc-8WgZUMU',
    appId: '1:539867176389:android:c277de9803e6d77611bfac',
    messagingSenderId: '539867176389',
    projectId: 'noticefication-5db0f',
    databaseURL: 'https://noticefication-5db0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noticefication-5db0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8550HM791KtsuCFzdAYZ27bmGdOs8sSI',
    appId: '1:539867176389:ios:ac9a5f0bed2299af11bfac',
    messagingSenderId: '539867176389',
    projectId: 'noticefication-5db0f',
    databaseURL: 'https://noticefication-5db0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noticefication-5db0f.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8550HM791KtsuCFzdAYZ27bmGdOs8sSI',
    appId: '1:539867176389:ios:5b8aac0d3264efff11bfac',
    messagingSenderId: '539867176389',
    projectId: 'noticefication-5db0f',
    databaseURL: 'https://noticefication-5db0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noticefication-5db0f.appspot.com',
    iosBundleId: 'com.example.push.RunnerTests',
  );
}
